name: Build and Deploy to Dataflow

on:
  push:
    branches:
      - main


env:
    PROJECT_ID: ${{ secrets.PROJECT_ID }}
    RUN_REGION: us-east1
    SERVICE_NAME: "data-ingestion-job"
    WORKER_REGION: us-east1
    WORKER_MACHINE_TYPE: e2-medium
    NUM_WORKERS: 1
    TEMP_LOCATION: gs://nashtech-ai-dev-389315/staging_location
    STAGING_LOCATION: gs://nashtech-ai-dev-389315/temp_location

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - run: mvn clean install
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: data-ingestion-1.0-SNAPSHOT.jar
          path: target/
  build-docker-image:
    name: build-docker
    needs: setup-build-deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Retrieve saved jar
        uses: actions/download-artifact@v2
        with:
          name: data-ingestion-1.0-SNAPSHOT.jar
          path: target/
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: |
          gcloud auth configure-docker us-docker.pkg.dev
      # Build the Docker image
      - name: Build
        run: |
          docker build -t us-docker.pkg.dev/$PROJECT_ID/docker-images/data-ingestion-github:latest -f Dockerfile .

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |
          docker push us-docker.pkg.dev/$PROJECT_ID/docker-images/data-ingestion-github:latest
            # Push the Docker image to Google Container Registry
      - name: Build Flex Template
        run: |
          gcloud dataflow flex-template build gs://nashtech-ai-dev-389315/templates/run_template_github.json --image us-docker.pkg.dev/$PROJECT_ID/docker-images/data-ingestion-github:latest --sdk-language JAVA
      - name: Run Flex Template
        run: |
          gcloud dataflow flex-template run "data-ingestion-job-$(date +%Y-%m-%d)" \
            --template-file-gcs-location=gs://nashtech-ai-dev-389315/templates/run_template_github.json \
            --worker-region=$WORKER_REGION \
            --worker-machine-type=$WORKER_MACHINE_TYPE \
            --region=$RUN_REGION \
            --service-account-email=${{ secrets.SA_EMAIL }} \
            --num-workers=$NUM_WORKERS \
            --parameters gcpProject=$PROJECT_ID \
            --parameters tempLocation=$TEMP_LOCATION \
            --parameters stagingLocation=$STAGING_LOCATION